# Generated by Django 4.2.6 on 2023-10-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
